//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserClient.ParserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bank", Namespace="http://schemas.datacontract.org/2004/07/ParsingService")]
    [System.SerializableAttribute()]
    public partial class Bank : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EurBuyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EurSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RubBuyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RubSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsdBuyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsdSaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EurBuy {
            get {
                return this.EurBuyField;
            }
            set {
                if ((object.ReferenceEquals(this.EurBuyField, value) != true)) {
                    this.EurBuyField = value;
                    this.RaisePropertyChanged("EurBuy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EurSale {
            get {
                return this.EurSaleField;
            }
            set {
                if ((object.ReferenceEquals(this.EurSaleField, value) != true)) {
                    this.EurSaleField = value;
                    this.RaisePropertyChanged("EurSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RubBuy {
            get {
                return this.RubBuyField;
            }
            set {
                if ((object.ReferenceEquals(this.RubBuyField, value) != true)) {
                    this.RubBuyField = value;
                    this.RaisePropertyChanged("RubBuy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RubSale {
            get {
                return this.RubSaleField;
            }
            set {
                if ((object.ReferenceEquals(this.RubSaleField, value) != true)) {
                    this.RubSaleField = value;
                    this.RaisePropertyChanged("RubSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsdBuy {
            get {
                return this.UsdBuyField;
            }
            set {
                if ((object.ReferenceEquals(this.UsdBuyField, value) != true)) {
                    this.UsdBuyField = value;
                    this.RaisePropertyChanged("UsdBuy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsdSale {
            get {
                return this.UsdSaleField;
            }
            set {
                if ((object.ReferenceEquals(this.UsdSaleField, value) != true)) {
                    this.UsdSaleField = value;
                    this.RaisePropertyChanged("UsdSale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParserService.IParsingService")]
    public interface IParsingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParsingService/ParseThePages", ReplyAction="http://tempuri.org/IParsingService/ParseThePagesResponse")]
        ParserClient.ParserService.Bank[] ParseThePages(string[] urls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParsingService/ParseThePages", ReplyAction="http://tempuri.org/IParsingService/ParseThePagesResponse")]
        System.Threading.Tasks.Task<ParserClient.ParserService.Bank[]> ParseThePagesAsync(string[] urls);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParsingServiceChannel : ParserClient.ParserService.IParsingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParsingServiceClient : System.ServiceModel.ClientBase<ParserClient.ParserService.IParsingService>, ParserClient.ParserService.IParsingService {
        
        public ParsingServiceClient() {
        }
        
        public ParsingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParsingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParsingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParsingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ParserClient.ParserService.Bank[] ParseThePages(string[] urls) {
            return base.Channel.ParseThePages(urls);
        }
        
        public System.Threading.Tasks.Task<ParserClient.ParserService.Bank[]> ParseThePagesAsync(string[] urls) {
            return base.Channel.ParseThePagesAsync(urls);
        }
    }
}
